### ISSUE TITLE
Fix dependencies before make pull request

### ISSUE THREAD

**Issue by kamataryo** [geolonia/docs.geolonia.com#2]
The branch should be reviewed and merged after Embed API CDN updated.
https://github.com/geolonia/docs.geolonia.ocm/compare/tilecloud-to-geolonia?expand=1

TODOs:
- [ ] Deploy serverless of api.geolonia.com
- [ ] Fix domain
- [ ] Set redirect from `api.tilecloud.io/*` to `api.geolonia.com`

**Comment by miya0001** [comment]
Closed in favor. 😊
