### ISSUE TITLE
サインアップボタンを目立つ位置に追加

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/docs.geolonia.com#26]
ドキュメンテーションサイトには、他のランディングページ等から来る人もいるので。

<img width="1311" alt="スクリーンショット 2021-08-23 14 47 40" src="https://user-images.githubusercontent.com/1124652/130396872-83afbccc-a1b6-4876-b8a4-f06a04a710fd.png">

**Comment by kogumari** [comment]
「ログイン」もあるといいのかなと思いました！

**Comment by gatespace** [comment]
外からやってきましたこんばんは。
ドキュメント見ながらダッシュボード入りたいので、ドキュメントにログインとサインインのリンク作ってください。
ドキュメントから geolonia.com （元のサイト）に戻るリンクもないので、ログインしたいときにつらいです。

**Comment by naogify** [comment]
@gatespace 
フィードバックありがとうございます！こちら対応致します。

**Comment by naogify** [comment]
@gatespace 
こちら #29 で修正しましたので、issue をクローズします。
ありがとうございました！
