### ISSUE TITLE
[Cookbook] マーカーをカスタマイズの CodePenが壊れている

### ISSUE THREAD

**Issue by naogify** [geolonia/docs.geolonia.com#82]
和歌山県の GitHubがデータソースだけれど、リンク切れになっている
https://docs.geolonia.com/cookbook/003/
https://codepen.io/geolonia/pen/zYGRgdq?editors=1010

**Comment by champierre** [comment]
すでに修正済みですよね？ @naogify 
クローズしてもいいですか？

**Comment by naogify** [comment]
@champierre 
こちらデータソースを別のものに変更する事で修正しました。修正したのでクローズしますね。
https://codepen.io/geolonia/pen/zYGRgdq
