### ISSUE TITLE
カスタムアイコンの一覧がほしい

### ISSUE THREAD

**Issue by champierre** [geolonia/docs.geolonia.com#96]
basic で使用できるカスタムアイコンの一覧がほしい

https://docs.geolonia.com/geojson/marker-symbols とかにつくるのがいいか？

**Comment by keichan34** [comment]
置く場所→ geojson/marker-symbol.html とか
クライアントサイドでsvg読み込む？それかスプライトシートを読み込む？

**Comment by champierre** [comment]
https://docs.geolonia.com/geojson/marker-symbol/ に追加されたのでクローズします。
